artifact_uri: mlflow-artifacts:/526375960256618681/de6f9ce71d4b4f209688aa762dbf9bc9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '526375960256618681'
lifecycle_stage: active
run_id: de6f9ce71d4b4f209688aa762dbf9bc9
run_name: adventurous-kite-565
source_name: ''
source_type: 4
source_version: ''
start_time: 1772714333096
status: 1
tags: []
user_id: codespace
